# Generated by Django 2.0 on 2017-12-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_cases_vote_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='rating_num',
            field=models.IntegerField(default=1, verbose_name='评分人数'),
        ),
        migrations.AddField(
            model_name='cases',
            name='sum_rating_score',
            field=models.IntegerField(default=3, verbose_name='所有评分总和'),
        ),
    ]
