# Generated by Django 2.0 on 2018-01-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_auto_20171213_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
    ]
