# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexad',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='indexad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='cases_num',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='cases_sn',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='ship_free',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='shop_price',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='sold_num',
        ),
        migrations.DeleteModel(
            name='IndexAd',
        ),
    ]
