# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20171114_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cases',
        ),
        migrations.AddField(
            model_name='banner',
            name='hyperlink',
            field=models.CharField(default='/index', max_length=200, verbose_name='超链接地址'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='暂无标题', max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='cases_desc',
            field=models.TextField(max_length=50000, verbose_name='案例正文内容'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='cases_front_image',
            field=models.CharField(default='/static/image/fail.jpg', max_length=200, verbose_name='封面图URL'),
        ),
    ]
