# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20171124_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='reply_num',
            field=models.IntegerField(default=0, verbose_name='回复数'),
        ),
    ]
