# Generated by Django 2.0 on 2017-12-10 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='问题名')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('reply_num', models.IntegerField(default=0, verbose_name='回复数')),
                ('cases_brief', models.TextField(max_length=500, verbose_name='问题简短描述')),
                ('cases_desc', models.TextField(max_length=50000, verbose_name='问题正文内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='QuestionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '问题状态',
                'verbose_name_plural': '问题状态',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionState', verbose_name='案例类目'),
        ),
    ]
