# Generated by Django 2.0 on 2017-12-10 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_num', models.IntegerField(default=0, verbose_name='回复数')),
                ('vote_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('answer_desc', models.TextField(max_length=50000, verbose_name='回答正文内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
            },
        ),
        migrations.CreateModel(
            name='SubAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='位于回答跟帖中的索引下标')),
                ('sub_answer_desc', models.TextField(max_length=50000, verbose_name='跟帖正文内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answers', verbose_name='父回答')),
            ],
            options={
                'verbose_name': '回答跟帖',
                'verbose_name_plural': '回答跟帖',
            },
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='cases_brief',
            new_name='question_brief',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='cases_desc',
            new_name='question_desc',
        ),
        migrations.AddField(
            model_name='questions',
            name='label_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标签名1'),
        ),
        migrations.AddField(
            model_name='questions',
            name='label_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标签名2'),
        ),
        migrations.AddField(
            model_name='questions',
            name='label_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标签名3'),
        ),
        migrations.AddField(
            model_name='questions',
            name='label_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标签名4'),
        ),
        migrations.AddField(
            model_name='questions',
            name='label_5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标签名5'),
        ),
        migrations.AddField(
            model_name='questions',
            name='vote_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionState', verbose_name='问题状态'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions', verbose_name='问题'),
        ),
    ]
