# Generated by Django 2.0 on 2017-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20171210_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='state',
            field=models.IntegerField(choices=[(1, '待解决'), (2, '已解决'), (3, '悬赏')], default=1, help_text='问题状态', verbose_name='问题状态'),
        ),
    ]
