# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20171021_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleavingmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLeavingMessage',
        ),
    ]
